version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

  web-shop-category:
     build:
       context: ./microservices/CategoryService
       dockerfile: ./Dockerfile
     ports:
       - "8889:8080" # Increment on 8888
     environment:
       - SPRING_DATASOURCE_URL=jdbc:mysql://web-shop-db-image:3306/categorydb
     networks:
       local_dev_net:
           aliases:
               - category

  web-shop-product:
     build:
       context: ./microservices/ProductService
       dockerfile: ./Dockerfile
     ports:
       - "8890:8080"
     environment:
       - SPRING_DATASOURCE_URL=jdbc:mysql://web-shop-db-image:3306/productdb
     networks:
       local_dev_net:
         aliases:
           - product

networks:
  local_dev_net:
    driver: bridge
